### ISSUE TITLE
How to upgrade packages?

### ISSUE THREAD

**Issue by babygau** [kclejeune/system#111]
Hi @kclejeune, I hope you are doing well. I'm wondering what's your recommendation to upgrade the packages?

Here is what I did, but not sure it's   right or wrong

```
nix flake update
nix build .#host
darwin-rebuild swith --flake .#host
```

And how about upgrade a single package only? For example I want to upgrade Neovim.

**Comment by kclejeune** [comment]
> Hi @kclejeune, I hope you are doing well. I'm wondering what's your recommendation to upgrade the packages?
> 
> Here is what I did, but not sure it's   right or wrong
> 
> ```
> nix flake update
> nix build .#host
> darwin-rebuild swith --flake .#host
> ```
> 
> And how about uograde a single package only? For example I want to upgrade Neovim.

Probably something like

`nix flake lock --update-input neovim-nightly-overlay`

**Comment by babygau** [comment]
Thank you!
