### ISSUE TITLE
`home.packages` vs `users.packages`

### ISSUE THREAD

**Issue by babygau** [kclejeune/system#112]
Hi @kclejeune, today I got sometimes to learn me some Nix. Pretty happy with my current config based on yours. Thank you so much for that. However, my today question is, I see you use `home-manager` to manage user installed packages `home.packages = with pkgs; [...];`. What make it different from `users.users.{name}.packages`?

**Comment by kclejeune** [comment]
> I see you use `home-manager` to manage user installed packages `home.packages = with pkgs; [...];`. 

This is the property to install packages within a home manager configuration. 

> What make it different from `users.users.{name}.packages`? 

Not sure what you mean by this? There's `environment.systemPackages` which lives in nix-darwin, outside of home manager.

**Comment by babygau** [comment]
Tks you. Could you care to explain this line?
![Screenshot_20210720-090832_GitHub.jpg](https://user-images.githubusercontent.com/1514823/126238710-c4b64b29-320b-416e-931f-b6c5a3ed317d.jpg)

Is it correct that this also extend `nixpkgs` lib to your custom lib and HM libs such as mkOutOfStoreSymLink also available as `lib.file.mkOutOfStoreSymLink`? What is `final` role?

**Comment by kclejeune** [comment]
> Tks you. Could you care to explain this line?
> ![Screenshot_20210720-090832_GitHub.jpg](https://user-images.githubusercontent.com/1514823/126238710-c4b64b29-320b-416e-931f-b6c5a3ed317d.jpg)
> 
> Is it correct that this also extend `nixpkgs` lib to your custom lib and HM libs such as mkOutOfStoreSymLink also available as `lib.file.mkOutOfStoreSymLink`? What is `final` role?

This is meant to merge `nixpkgs.lib`, my own custom `./lib`, and home manager's `lib` into a single shared set of functions that I can use anywhere. Honestly I'm not totally sure how the final: prev semantics work; I grabbed the example from documentation for the extend function.

**Comment by babygau** [comment]
Thank you @kclejeune, I learnt a lot from your config and really appreciate that. Could have asked you more but I don't have the computer with me so it's difficult to type on mobile 😃
