### ISSUE TITLE
darwin-rebuild: command not found

### ISSUE THREAD

**Issue by Eason0210** [kclejeune/system#161]
Hi @kclejeune ,

Thanks for sharing your nix configuration, it is very nice config.
But after bootstrap on my MacBook with `nix --extra-experimental-features "nix-command flakes" develop -c sysdo bootstrap --darwin MacBook`, it works as expected.

but when I try to use ` sysdo switch MacBook` after update my configuration, it will got this error.
```shell
❯ sysdo switch MacBook
> darwin-rebuild switch --flake .#MacBook --show-trace
sh: darwin-rebuild: command not found
```

To make it work , I need to run this in terminal manually

```sh
export PATH="/run/current-system/sw/bin:$PATH"
export PATH="/etc/profiles/per-user/aqua0210/bin:$PATH"
```
How do you make `sysdo` work without manually  add PATH?

**Comment by kclejeune** [comment]
You need to start a new shell. The bootstrap command should activate the initial generation, but you need to open a new shell to reload the zshrc. The path should be included in this.

**Comment by Eason0210** [comment]
I restart a new shell, and it is the same result.  
I also  found that the `~/.zshrc ` is empty

**Comment by kclejeune** [comment]
> I restart a new shell, and it is the same result.  
> 
> I also  found that there is no this file  `~/.zshrc ` 
> 
> 
> 
> But there is an `~/.zshenv `with content:
> 
> ```
> 
> source $HOME/.config/zsh/.zshenv
> 
> ```

In the .nixpkgs directory, is there a folder named ./result? If so, run `./result/activate-user && ./result/activate`

**Comment by Eason0210** [comment]
Hi @kclejeune 

Thanks for your help. 
` ~/.config/zsh/.zshrc` do existed.

Now I have fixed issue with enable  `programs.zsh ` in  `common.nix `.
Everything is working well now!

It was conflicted  with nix 2.4 before, now the bug have been fixed. That's why  I disabled `programs.zsh ` before.
