### ISSUE TITLE
Comma repository has been move to nix- community

### ISSUE THREAD

**Issue by Eason0210** [kclejeune/system#166]
Hi @kclejeune ，

The comma repository has been transfer to nix-community：
https://github.com/nix-community/comma

**Comment by kclejeune** [comment]
> Hi @kclejeune ，
> 
> 
> 
> The comma repository has been transfer to nix-community：
> 
> https://github.com/nix-community/comma

Thanks for the heads up! Looking forward to seeing more support for this tool as nix continues to evolve.
