### ISSUE TITLE
Nixos password hash

### ISSUE THREAD

**Issue by crazy-matt** [kclejeune/system#211]
Hi Kennan,

First of all, thanks a lot for sharing your configuration. I started learning Nix just about a week ago and I'm learning a lot reading through it.

I was curious about your nixos module password. How did you get its hash [here](https://github.com/kclejeune/system/blob/fea698bee9bdc8e33ff56ecf543c3e94567a7299/modules/nixos/default.nix#LL27C30-L27C30)

**Comment by crazy-matt** [comment]
Ok I think `mkpasswd -m sha-512` should do it. I've seen some threads around mosquitto_passwd explaining that mkpasswd doesn't make it but it seems fixed now.

**Comment by kclejeune** [comment]
> Ok I think `mkpasswd -m sha-512` should do it. I've seen some threads around mosquitto_passwd explaining that mkpasswd doesn't make it but it seems fixed now.

Whoops, sorry! I didn't see this until just now - I'm pretty sure I originally copied whatever was in the NixOS option docs, but I believe that command is correct :) 

Feel free to let me know if you need any more help!
