### ISSUE TITLE
Are you planning to migrate your system config to flake-parts?

### ISSUE THREAD

**Issue by bangedorrunt** [kclejeune/system#236]
Hi @kclejeune,

For your reference, please see https://github.com/bangedorrunt/nix/tree/flake-parts

Most of my code is trial and error but it worked OK for me. I'm looking forward to hearing your response. Also, your suggestion for any improvement is really appreciated!

**Comment by kclejeune** [comment]
> Hi @kclejeune,
> 
> 
> 
> For your reference, please see https://github.com/bangedorrunt/nix/tree/flake-parts
> 
> 
> 
> Most of my code is trial and error but it worked OK for me. I'm looking forward to hearing your response. Also, your suggestion for any improvement is really appreciated!

Probably not. It looks like a decent utility lib and I think your implementation looks fine, but one of my high level goals is to keep this as close to a vanilla flake as possible. 

I think keeping things simple is generally better for people who want to learn from my repository, and more importantly for keeping my sanity when I'm adding new things to my config. It's much easier to debug something I wrote than to try and figure out if there's a bug elsewhere :)
