### ISSUE TITLE
Can I use this to manage system configuration declaratively on Debian?

### ISSUE THREAD

**Issue by brandonros** [kclejeune/system#271]
```
root@customer-portal:/root# history
    1  apt update
    2  apt-get upgrade
    3  apt-get dist-upgrade
    4  apt-get install nix
    6  sudo nano /etc/nix/nix.conf # add experimental-features = nix-command flakes
    7  sudo systemctl restart nix-daemon
    8  nix run nixpkgs#hello
```

After this, how would I make like a flake or a config file or whatever and be like "ok, I want to add a system user" and then use nix to deploy it/apply it? Or can I not do this because I'm not using NixOS?

**Comment by kclejeune** [comment]
I don’t think so - you could use home-manager to declaratively manage user configuration (which is generally how I use this on Debian derivatives) but system level config still needs to happen with standard Debian tools. 

I know there is an effort called “system-manager” (maybe from numtide?) to develop something like nix-Darwin for non-NixOS Linux distros that could allow for this in the future though!

**Comment by brandonros** [comment]
So I’m stuck with Ansible for now I guess? Unless you know anything better?

Thanks for responding!

**Comment by kclejeune** [comment]
Unfortunately yes, probably. You could consider adding your sensible playbook invocations on home-manager system activation or maybe even add a module for running “declarative” system playbooks? 

Ultimately something like https://github.com/numtide/system-manager is probably the “correct” path forward to contribute that natively, but an ansible module would certainly be less effort initially.
