### ISSUE TITLE
`nix run .#sysdo bootstrap` + `darwin-rebuild` Errors

### ISSUE THREAD

**Issue by face0b1101** [kclejeune/system#321]
Hi, I'm new to nix and I just found your config - thanks for open sourcing it!

I'm trying your configs out on an M3 Macbook and I'm falling at the first hurdle...

I have modified `flake.nix` to change the username to my local username, but when I run `nix run .#sysdo bootstrap` it errors out with:

```sh
error: flake 'github:kclejeune/system' does not provide attribute 'packages.aarch64-darwin.darwinConfigurations.will@aarch64-darwin.config.system.build.toplevel', 'legacyPackages.aarch64-darwin.darwinConfigurations.will@aarch64-darwin.config.system.build.toplevel' or 'darwinConfigurations.will@aarch64-darwin.config.system.build.toplevel'
```

and
  
```
FileNotFoundError: [Errno 2] No such file or directory: './result/sw/bin/darwin-rebuild'
```

I am far from competent in nix at the moment, but I would have thought that the configurations would be for `<username>@<hostname>`, not `<username>@<arch>`. Should I have made some other modifications within `flake.nix`?

At the moment I'm just looking to get this up and running, then work my way through the config to customise it to my needs. Starting with a working config would make it a lot easier to learn than the current trial and error I've been going through over the last few days.

Full error: 

```sh
error: flake 'github:kclejeune/system' does not provide attribute 'packages.aarch64-darwin.darwinConfigurations.will@aarch64-darwin.config.system.build.toplevel', 'legacyPackages.aarch64-darwin.darwinConfigurations.will@aarch64-darwin.config.system.build.toplevel' or 'darwinConfigurations.will@aarch64-darwin.config.system.build.toplevel'
$ ./result/sw/bin/darwin-rebuild switch --flake github:kclejeune/system#will@aarch64-darwin
Traceback (most recent call last):

  File "/nix/store/6c3arqnvmfr2r0p42c9k6vwzydliccmr-sysdo/bin/sysdo", line 331, in <module>
    app()

  File "/nix/store/6c3arqnvmfr2r0p42c9k6vwzydliccmr-sysdo/bin/sysdo", line 137, in bootstrap
    run_cmd(

  File "/nix/store/6c3arqnvmfr2r0p42c9k6vwzydliccmr-sysdo/bin/sysdo", line 72, in run_cmd
    else subprocess.run(cmd, shell=False)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/nix/store/kqsqlfvvr4gr3q83vl43gprk47rbsc5d-python3-3.11.9/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/nix/store/kqsqlfvvr4gr3q83vl43gprk47rbsc5d-python3-3.11.9/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,

  File "/nix/store/kqsqlfvvr4gr3q83vl43gprk47rbsc5d-python3-3.11.9/lib/python3.11/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)

FileNotFoundError: [Errno 2] No such file or directory: './result/sw/bin/darwin-rebuild'
```

**Comment by kclejeune** [comment]
> Hi, I'm new to nix and I just found your config - thanks for open sourcing it!
> 
> 
> 
> I'm trying your configs out on an M3 Macbook and I'm falling at the first hurdle...
> 
> 
> 
> I have modified `flake.nix` to change the username to my local username, but when I run `nix run .#sysdo bootstrap` it errors out with:
> 
> 
> 
> ```sh
> 
> error: flake 'github:kclejeune/system' does not provide attribute 'packages.aarch64-darwin.darwinConfigurations.will@aarch64-darwin.config.system.build.toplevel', 'legacyPackages.aarch64-darwin.darwinConfigurations.will@aarch64-darwin.config.system.build.toplevel' or 'darwinConfigurations.will@aarch64-darwin.config.system.build.toplevel'
> 
> ```
> 
> 
> 
> and
> 
>   
> 
> ```
> 
> FileNotFoundError: [Errno 2] No such file or directory: './result/sw/bin/darwin-rebuild'
> 
> ```
> 
> 
> 
> I am far from competent in nix at the moment, but I would have thought that the configurations would be for `<username>@<hostname>`, not `<username>@<arch>`. Should I have made some other modifications within `flake.nix`?
> 
> 
> 
> At the moment I'm just looking to get this up and running, then work my way through the config to customise it to my needs. Starting with a working config would make it a lot easier to learn than the current trial and error I've been going through over the last few days.
> 
> 
> 
> Full error: 
> 
> 
> 
> ```sh
> 
> error: flake 'github:kclejeune/system' does not provide attribute 'packages.aarch64-darwin.darwinConfigurations.will@aarch64-darwin.config.system.build.toplevel', 'legacyPackages.aarch64-darwin.darwinConfigurations.will@aarch64-darwin.config.system.build.toplevel' or 'darwinConfigurations.will@aarch64-darwin.config.system.build.toplevel'
> 
> $ ./result/sw/bin/darwin-rebuild switch --flake github:kclejeune/system#will@aarch64-darwin
> 
> Traceback (most recent call last):
> 
> 
> 
>   File "/nix/store/6c3arqnvmfr2r0p42c9k6vwzydliccmr-sysdo/bin/sysdo", line 331, in <module>
> 
>     app()
> 
> 
> 
>   File "/nix/store/6c3arqnvmfr2r0p42c9k6vwzydliccmr-sysdo/bin/sysdo", line 137, in bootstrap
> 
>     run_cmd(
> 
> 
> 
>   File "/nix/store/6c3arqnvmfr2r0p42c9k6vwzydliccmr-sysdo/bin/sysdo", line 72, in run_cmd
> 
>     else subprocess.run(cmd, shell=False)
> 
>          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
> 
> 
>   File "/nix/store/kqsqlfvvr4gr3q83vl43gprk47rbsc5d-python3-3.11.9/lib/python3.11/subprocess.py", line 548, in run
> 
>     with Popen(*popenargs, **kwargs) as process:
> 
>          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
> 
> 
>   File "/nix/store/kqsqlfvvr4gr3q83vl43gprk47rbsc5d-python3-3.11.9/lib/python3.11/subprocess.py", line 1026, in __init__
> 
>     self._execute_child(args, executable, preexec_fn, close_fds,
> 
> 
> 
>   File "/nix/store/kqsqlfvvr4gr3q83vl43gprk47rbsc5d-python3-3.11.9/lib/python3.11/subprocess.py", line 1955, in _execute_child
> 
>     raise child_exception_type(errno_num, err_msg, err_filename)
> 
> 
> 
> FileNotFoundError: [Errno 2] No such file or directory: './result/sw/bin/darwin-rebuild'
> 
> ```

Hey, sorry I'm just now seeing this! This is a good question.

In short, I have this set up so that it applies across many hosts, but you're correct that user@arch is a little unconventional. This is mainly just so that I can easily auto-detect users and host systems for my personal/work machines, but there's not a good reason beyond that. 

You can pass an extra argument to specify the specific host you want to build to `sysdo`, which should hopefully get the bootstrap process to work? If not let me know and I can try to help 🙂
